# Inhouse to CView (IRCH)
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_inhouse/target_cview/config_cfg.py --source_dataset inhouse --target_dataset cview --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_inhouse/source_in.pth --output_dir ./exps/source_inhouse/target_cview/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.001 --expert_embed_dir ./expert_embeddings --conf_update_algo const_thresh

# Inhouse to INBreast
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_inhouse/target_inbreast/config_cfg.py --source_dataset inhouse --target_dataset inbreast --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_inhouse/source_in.pth --output_dir ./exps/source_inhouse/target_inbreast/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.06 --expert_embed_dir ./expert_embeddings --conf_update_algo const_thresh

# Inhouse to DDSM
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_inhouse/target_ddsm/config_cfg.py --source_dataset inhouse --target_dataset ddsm --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_inhouse/source_in.pth --output_dir ./exps/source_inhouse/target_ddsm/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.06 --expert_embed_dir ./expert_embeddings --conf_update_algo const_thresh

## NOTE: Use the hyperparameters as instructed in the paper's supplementary
# Sim10k to Cityscapes
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_sim10k/target_cityscapes/config_cfg.py --source_dataset sim10k --target_dataset cityscapes_target --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_sim10k/source_in.pth --output_dir ./exps/source_sim10k/target_cityscapes/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.1 --expert_embed_dir ./expert_embeddings --conf_update_algo raise_slowly

# KITTI to Cityscapes
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_sim10k/target_cityscapes/config_cfg.py --source_dataset sim10k --target_dataset cityscapes_target --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_sim10k/source_in.pth --output_dir ./exps/source_sim10k/target_cityscapes/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.1 --expert_embed_dir ./expert_embeddings --conf_update_algo raise_slowly

# Cityscapes to FoggyCityscapes
CUDA_VISIBLE_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 11002 main.py --config_file ./weights/source_sim10k/target_cityscapes/config_cfg.py --source_dataset sim10k --target_dataset cityscapes_target --coco_path /home/kartik_anand/scratch/kstyles/miccai/DA_DATASETS/Dmaster_Data/ --pretrain_model_path ./weights/source_sim10k/source_in.pth --output_dir ./exps/source_sim10k/target_cityscapes/ --find_unused_params --module_type student_with_expert_module --adapt --temp 1.0 --memory_bank_size 1 --lambda_eckd 1.0 --init_threshold 0.1 --expert_embed_dir ./expert_embeddings --conf_update_algo raise_slowly